### ISSUE TITLE
Bug with eval function

### ISSUE THREAD

**Issue by alexanderimanicowenrivers** [facebookresearch/kbc#11]
I set up the conda enviroment exactly as specified, however, there seems to be an evaluation bug (on the third epoch) when I run the below command. 

`python3 kbc/learn.py --dataset FB237 --model ComplEx --regularizer N3 --optimizer Adagrad --rank` 

<img width="1424" alt="eval bug" src="https://user-images.githubusercontent.com/26690606/59655113-2caadc00-91d4-11e9-884d-c92ac1556e6c.png">

**Comment by timlacroix** [comment]
Should be fixed in the latest commit. Thanks

**Comment by alexanderimanicowenrivers** [comment]
wow, amazingly quick! Thanks!
