### ISSUE TITLE
How to run your code?

### ISSUE THREAD

**Issue by ooCher** [facebookresearch/kbc#14]
I'm sorry to bother you, I want to know how to get the results after creating the files required to compute the filtered metrics. Could you help me?

**Comment by timlacroix** [comment]
Hi,
You mean for a new dataset?
You can add it as a dataset in the dataset.py file (not ideal. If you're
going to add many dataset and use the same metrics on all of them, just
create a dataset class that takes the name of the dataset as an arg).

Then in the main file, import your new dataset class and make it accessible
for the right command line argument.

Does this answer your question?

Le mar. 24 sept. 2019 à 08:20, ookangithub <notifications@github.com> a
écrit :

**Comment by ooCher** [comment]
Thank you for your reply. I mean that I don't know how to see the performances. After I run the "process_datasets.py",what should I do to get the perfomances?




------------------ 原始邮件 ------------------
发件人: "timlacroix"<notifications@github.com>;
发送时间: 2019年9月24日(星期二) 下午2:53
收件人: "facebookresearch/kbc"<kbc@noreply.github.com>;
抄送: "期待未来"<1269117483@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [facebookresearch/kbc] How to run your code? (#14)



Hi,
 You mean for a new dataset?
 You can add it as a dataset in the dataset.py file (not ideal. If you're
 going to add many dataset and use the same metrics on all of them, just
 create a dataset class that takes the name of the dataset as an arg).
 
 Then in the main file, import your new dataset class and make it accessible
 for the right command line argument.
 
 Does this answer your question?
 
 Le mar. 24 sept. 2019 à 08:20, ookangithub <notifications@github.com> a
 écrit :

**Comment by timlacroix** [comment]
Oops.

Sorry, I didn't realize  this was gone from the Readme.

```
python kbc/learn.py --dataset FB15K --model ComplEx --rank 2000 --optimizer
Adagrad --learning_rate 1e-2 --batch_size 100 --regularizer N3 --reg 5e-3
--reciprocals 1 --max_epochs 10 --valid 1
```

Is the command that was there before. Feel free to adapt it to the
parameters in the tables.

Le mar. 24 sept. 2019 à 09:05, ookangithub <notifications@github.com> a
écrit :

**Comment by ooCher** [comment]
Thanks a lot.




------------------ 原始邮件 ------------------
发件人: "timlacroix"<notifications@github.com>;
发送时间: 2019年9月24日(星期二) 下午3:10
收件人: "facebookresearch/kbc"<kbc@noreply.github.com>;
抄送: "期待未来"<1269117483@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [facebookresearch/kbc] How to run your code? (#14)



Oops.
 
 Sorry, I didn't realize  this was gone from the Readme.
 
 ```
 python kbc/learn.py --dataset FB15K --model ComplEx --rank 2000 --optimizer
 Adagrad --learning_rate 1e-2 --batch_size 100 --regularizer N3 --reg 5e-3
 --reciprocals 1 --max_epochs 10 --valid 1
 ```
 
 Is the command that was there before. Feel free to adapt it to the
 parameters in the tables.
 
 Le mar. 24 sept. 2019 à 09:05, ookangithub <notifications@github.com> a
 écrit :
