### ISSUE TITLE
Best results or hyper-parameters for N2 regularizer

### ISSUE THREAD

**Issue by zq0x7a0x71** [facebookresearch/kbc#15]
There is a regularizer called N2 in the code where $p=2$. However, its results are not included in the paper. Could you please provide the best results or the hyper-parameters for N2?  Thanks a lot.

**Comment by timlacroix** [comment]
Hi, sorry about that, this N2 implementation is wrong and shouldn't be there.
I added the N2 at some point to check whether or not using $p=3$ had a large influence (it did not). A correct implementation of the N2 norm would use :
\sum_r ||u_r||_2 ||v_r||_2 ||w_r||_2
And requires to add the weighting by empirical frequencies of appearance manually.

I will remove this regularizer and add the frobenius regularizer instead, which is used in the paper.

**Comment by zq0x7a0x71** [comment]
Why the N2 implementation is wrong? By Lemma 1 in the paper, these two implementations should be the same.

**Comment by timlacroix** [comment]
No. The code used the cubed two norms of the rows appearing in the batch.
By lemma 1, the 2-norm of the *full columns* should be used instead: 

for U, V and W *full* embedding matrices, this would be a valid N2 penalty:
```python
penalty = torch.norm(U, 2, 0)**3 + torch.norm(V, 2, 0)**3 + torch.norm(W, 2, 0)**3.
```
However, this penalty wouldn't be weighted. To use weighting (section 4.2), one would need to pre-compute the cubic root of the marginal probabilities of each subject (q_s), predicate (q_p) and object (q_o) and compute:

```python
penalty = torch.norm(q_s * U, 2, 0)**3 + torch.norm(q_p * V, 2, 0)**3 + torch.norm(q_o * W, 2, 0)**3.
```

Another way to achieve N2  penalty is described here: https://openreview.net/forum?id=rke2P1BFwS . (but with a different weighting scheme).

In my experience, N2 vs N3 on the datasets described in the paper didn't change the results much.
