### ISSUE TITLE
Output data

### ISSUE THREAD

**Issue by ksbsk** [facebookresearch/kbc#16]
Hello,

my goal is to produce Knowledge Graph embeddings to use later on in some downstream tasks.
So my idea was to use the kbc package for my datasets. The resulting graphs would be small, hence the kbc package seems like a great option! However, as opposed to [facebook's PBG](https://github.com/facebookresearch/PyTorch-BigGraph) I don't see any implemented mechanism for getting the output data (e.g. the HDF5 files, TSV).

Is there any pre-defined approach that you could suggest, something along [the lines](https://torchbiggraph.readthedocs.io/en/latest/downstream_tasks.html)?

If not, I suppose the only option for me is to start playing around with the kbc code...

**Comment by timlacroix** [comment]
Hi, yeah sorry this is a bit more barebones than PBG.
The upside is that the code is much more hackable :) 

If you want to save the embeddings, just add a torch.save(models, save_path) at the end of 

https://github.com/facebookresearch/kbc/blob/master/kbc/learn.py

Does that answer your question ?

If your datasets are tab separated files of the form 
lhs \t rel \t rhs \n 
then you can directly re-use
https://github.com/facebookresearch/kbc/blob/master/kbc/process_datasets.py
by just adding your dataset folder name line 110.

Don't hesitate if you have any other questions.

**Comment by timlacroix** [comment]
btw here is an issue with complete code for saving the model: 

https://github.com/facebookresearch/kbc/issues/13

**Comment by ksbsk** [comment]
Perfect, thanks so much for your prompt reply!
I'll play around with the solutions you proposed and let you know if they don't suffice (hope they do!).

Once again thanks a lot for your help!

**Comment by ksbsk** [comment]
Hi @timlacroix,

sorry to bother you again, but I wanted to let you know that saving and loading of the embeddings worked out, thanks! Now I have embeddings as NumPy arrays.
My next step is to match entity names with their corresponding vector representations.

So I was wondering if you could suggest a way to get a list of all entities by their corresponding ids and match them with their embedding?

**Comment by timlacroix** [comment]
Hi ! When a dataset is processed, I export two files rel_id and ent_id : 

https://github.com/facebookresearch/kbc/blob/master/kbc/process_datasets.py#L49-L54

So if you can find these two files, you can use less on them two see the format.

It's tab separated values, with one column being the id and the other the associated string in the original dataset :)

**Comment by timlacroix** [comment]
@ksbsk , did you manage to match entity names with ids ?

**Comment by ksbsk** [comment]
Hi @timlacroix,

sorry for the slow response, I was swamped with other work the past few days. And thanks a lot for your tips!

Yes, I've managed to find the files (in the Anaconda `site-packages` directory) and map entities to ids. I also tried to match entity names with their corresponding vector representations.
Something along these lines -- given the entity name I try to find its embedding:

```
df_ent = pd.read_csv("model/fb15k/kbc/ent_id", delimiter='\t', header=None, names=['node_name', 'node_id'])

node_names = df_ent.node_name.values
node_ids = df_ent.node_id.values

node_to_ix = dict(zip(node_names, node_ids))

lookup_tensor = torch.tensor([node_to_ix['/m/05hf_5']], dtype=torch.long).cuda()
node_embed = emb(lookup_tensor)

print(node_embed)
```

However, this is only true provided that the entity with id _i_ has its embedding stored in the _i_’th row of the embedding matrix.
Could you please confirm if this assumption is true @timlacroix?

**Comment by timlacroix** [comment]
Hi,
yes, entity with id _i_ is stored in the _i_'th row, so you should be good to go !

**Comment by ksbsk** [comment]
OK, great, thanks for the confirmation!
I think we can close the issue now.

Have a good day!

**Comment by dejuzhang** [comment]
hello,i have the same problem,do you save the whole model using 'torch.save(model)' or just save the 'mode.state_dict()'.
besides,i wonder what kind of type of file i should save. i try to save .pkl but i can't load it.
sorry to bother you.

**Comment by ksbsk** [comment]
Yes, as far as I remember I used torch.save(model.state_dict(), model_path), where model_path is just a path where the model should be stored. A common PyTorch convention is to save models using either a .pt or .pth file extension.

"Saving the model’s state_dict with the torch.save() function will give you the most flexibility for restoring the model later. This is the recommended method for saving models, because it is only really necessary to save the trained model’s learned parameters. When saving and loading an entire model, you save the entire module using Python’s [pickle](https://docs.python.org/3/library/pickle.html) module. Using this approach yields the most intuitive syntax and involves the least amount of code. The disadvantage of this approach is that the serialized data is bound to the specific classes and the exact directory structure used when the model is saved. The reason for this is because pickle does not save the model class itself. Rather, it saves a path to the file containing the class, which is used during load time. Because of this, your code can break in various ways when used in other projects or after refactors. In this recipe, we will explore both ways on how to save and load models for inference."

https://pytorch.org/tutorials/recipes/recipes/saving_and_loading_models_for_inference.html

Hope this helps!

**Comment by dejuzhang** [comment]
thank you very much！！thank u
