### ISSUE TITLE
Experiments with "standard" ComplEx

### ISSUE THREAD

**Issue by mhd0528** [facebookresearch/kbc#20]
Hi, I noticed that in your paper you mentioned that there were expeiments you conducted with "standard ComplEx_N3" and the results are better than original ComplEx model. May I ask what's the parameter you used for that model? Are you using F2 regularizer and how do you remove the "reciprocal" setting from your model? Thanks.

**Comment by timlacroix** [comment]
hello, 

to remove the reciprocal setting:
- in kbc/process_datasets.py, line 78 : remove `+ n_relations`
- in kbc/datasets.py: comment out line 47 and 72

I don't understand the question "Are you using F2 regularizer" ? if it's standard  ComplEx_N3, then it was regularized using N3 ?

**Comment by mhd0528** [comment]
Thanks for the response! About the second I probably confused myself. And the reciprocal question is clear now. Thanks again.
