### ISSUE TITLE
ModuleNotFoundError: No module named 'kbc.lib.bindings'

### ISSUE THREAD

**Issue by p6jain** [facebookresearch/kbc#4]
I followed all the steps reported in readme, I got the following error:

(kbc_env) prachi@gpu01:~/kbc$ python kbc/learning/learn.py --dataset FB15K --model ComplEx --rank 2000 --optimizer Adagrad --learning_rate 1e-2 --batch_size 100 --regularizer L3ComplEx --reg 5e-3 --learn_inverse_rels 1 --max_epochs 100 --valid 1
Traceback (most recent call last):
  File "kbc/learning/learn.py", line 16, in <module>
    from kbc.lib.bindings import (
ModuleNotFoundError: No module named 'kbc.lib.bindings'

Please help!

**Comment by timlacroix** [comment]
Hi,

Did you see any errors when running python setup.py install ?

thank you,

Tim'

**Comment by p6jain** [comment]
I did see some warnings (pasted below) but no errors.

**Details**
`
gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
`
`
python -c "import numpy;print(numpy.__version__)"
1.15.1
`
**Here is the snippet:**

gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -fpic -fPIC -Wformat -Wformat-se
curity -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -fpic -fPIC -fPIC -Ikbc/lib -I/home/prachi/anaconda3/envs/kbc_env2/lib/python3.6/site-packages/torch/lib/include -I/home/prachi/anaconda3/envs/kbc_en
v2/lib/python3.6/site-packages/numpy/core/include -I/home/prachi/related_work/kbc2/kbc/models/ -I/home/prachi/anaconda3/envs/kbc_env2/include/python3.6m -c kbc/lib/bindings.cpp -o build/temp.linux-x
86_64-3.6/kbc/lib/bindings.o -g -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/prachi/anaconda3/envs/kbc_env2/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1823:0,
                 from /home/prachi/anaconda3/envs/kbc_env2/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/prachi/anaconda3/envs/kbc_env2/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from kbc/lib/bindings.cpp:626:
/home/prachi/anaconda3/envs/kbc_env2/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY
_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -fpic -fPIC -Wformat -Wformat-se
curity -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -fpic -fPIC -fPIC -Ikbc/lib -I/home/prachi/anaconda3/envs/kbc_env2/lib/python3.6/site-packages/torch/lib/include -I/home/prachi/anaconda3/envs/kbc_en
v2/lib/python3.6/site-packages/numpy/core/include -I/home/prachi/related_work/kbc2/kbc/models/ -I/home/prachi/anaconda3/envs/kbc_env2/include/python3.6m -c kbc/lib/models.cpp -o build/temp.linux-x86
_64-3.6/kbc/lib/models.o -g -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -fpic -fPIC -Wformat -Wformat-se
curity -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -fpic -fPIC -fPIC -Ikbc/lib -I/home/prachi/anaconda3/envs/kbc_env2/lib/python3.6/site-packages/torch/lib/include -I/home/prachi/anaconda3/envs/kbc_en
v2/lib/python3.6/site-packages/numpy/core/include -I/home/prachi/related_work/kbc2/kbc/models/ -I/home/prachi/anaconda3/envs/kbc_env2/include/python3.6m -c kbc/lib/optimizer.cpp -o build/temp.linux-
x86_64-3.6/kbc/lib/optimizer.o -g -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -fpic -fPIC -Wformat -Wformat-se
curity -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -fpic -fPIC -fPIC -Ikbc/lib -I/home/prachi/anaconda3/envs/kbc_env2/lib/python3.6/site-packages/torch/lib/include -I/home/prachi/anaconda3/envs/kbc_en
v2/lib/python3.6/site-packages/numpy/core/include -I/home/prachi/related_work/kbc2/kbc/models/ -I/home/prachi/anaconda3/envs/kbc_env2/include/python3.6m -c kbc/lib/loss.cpp -o build/temp.linux-x86_6
4-3.6/kbc/lib/loss.o -g -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -fpic -fPIC -Wformat -Wformat-se
curity -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -fpic -fPIC -fPIC -Ikbc/lib -I/home/prachi/anaconda3/envs/kbc_env2/lib/python3.6/site-packages/torch/lib/include -I/home/prachi/anaconda3/envs/kbc_en
v2/lib/python3.6/site-packages/numpy/core/include -I/home/prachi/related_work/kbc2/kbc/models/ -I/home/prachi/anaconda3/envs/kbc_env2/include/python3.6m -c kbc/lib/regularizer.cpp -o build/temp.linu
x-x86_64-3.6/kbc/lib/regularizer.o -g -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -fpic -fPIC -Wformat -Wformat-se
curity -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -fpic -fPIC -fPIC -Ikbc/lib -I/home/prachi/anaconda3/envs/kbc_env2/lib/python3.6/site-packages/torch/lib/include -I/home/prachi/anaconda3/envs/kbc_en
v2/lib/python3.6/site-packages/numpy/core/include -I/home/prachi/related_work/kbc2/kbc/models/ -I/home/prachi/anaconda3/envs/kbc_env2/include/python3.6m -c kbc/lib/utils.cpp -o build/temp.linux-x86_
64-3.6/kbc/lib/utils.o -g -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
kbc/lib/utils.cpp: In function ‘void kbc::get_filtered_ranks(float*, size_t, size_t, std::vector<std::vector<long unsigned int> >&, int64_t*, int64_t*)’:
kbc/lib/utils.cpp:19:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(long int b = 0; b <  B; b++) {
                         ^
g++ -pthread -shared -L/home/prachi/anaconda3/envs/kbc_env2/lib -Wl,-rpath=/home/prachi/anaconda3/envs/kbc_env2/lib,--no-as-needed -z noexecstack -z relro -z now -fstack-protector build/temp.linux-x
86_64-3.6/kbc/lib/bindings.o build/temp.linux-x86_64-3.6/kbc/lib/models.o build/temp.linux-x86_64-3.6/kbc/lib/optimizer.o build/temp.linux-x86_64-3.6/kbc/lib/loss.o build/temp.linux-x86_64-3.6/kbc/l
ib/regularizer.o build/temp.linux-x86_64-3.6/kbc/lib/utils.o -L/home/prachi/anaconda3/envs/kbc_env2/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/kbc/lib/bindings.cpython-36m-x86_64-linux-gnu.so -W
l,-rpath,/home/prachi/anaconda3/envs/kbc_env2/lib/python3.6/site-packages/torch/lib /home/prachi/anaconda3/envs/kbc_env2/lib/python3.6/site-packages/torch/lib/libcaffe2.so /home/prachi/anaconda3/env
s/kbc_env2/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so -fopenmp

**Comment by timlacroix** [comment]
hmm that's weird then.can you import kbc at all ?

(in your snippet you're installing in kbc_env2 while your original error was using kbc_env. I assume that's harmless ?)

**Comment by p6jain** [comment]
(kbc_env2) prachi@gpu01:\~/related_work/kbc2/kbc$ python -c "import kbc"
#works fine
(kbc_env2) prachi@gpu01:\~/related_work/kbc2/kbc$ python -c "import kbc.lib"
#works fine
(kbc_env2) prachi@gpu01:\~/related_work/kbc2/kbc$ python -c "import kbc.lib.bindings"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'kbc.lib.bindings'

PS: I created another environment - and reinstalled everything - the error persists

**Comment by timlacroix** [comment]
Ok, thanks for the details. Looking into this today.

**Comment by timlacroix** [comment]
Ok, I suspect it's because you ran python inside the kbc folder and it loads the module from there, rather than site-packages. The bindings.so file is not where it should be inside the original folder structure, hence python doesn't find it.

Running python outside of the kbc folder fixed this issue for me. Can you confirm it is the same for you ?

**Comment by p6jain** [comment]
python -c "import kbc.lib.bindings" works inside kbc folder

**More details:**
(kbc_env2) prachi@gpu01:~/related_work/kbc2/kbc/kbc$ ls
data  datasets  __init__.py  learning  lib  __pycache__  scripts

(kbc_env2) prachi@gpu01:\~/related_work/kbc2/kbc/kbc$ python -c "import kbc.lib.bindings"
#works fine

(kbc_env2) prachi@gpu01:\~/related_work/kbc2/kbc/kbc$ cd ../

(kbc_env2) prachi@gpu01:\~/related_work/kbc2/kbc$ python -c "import kbc.lib.bindings"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'kbc.lib.bindings'

(kbc_env2) prachi@gpu01:~/related_work/kbc2$ python -c "import kbc.lib.bindings"
#works fine

(kbc_env2) prachi@gpu01:~/related_work/kbc2$ python learning/learn.py --dataset FB15K --model ComplEx --rank 2000 --optimizer Adagrad --learning_rate 1e-2 --batch_size 100 --regularizer L3ComplEx --reg 5e-3 --learn_inverse_rels 1 --max_epochs 100 --valid 1
python: can't open file 'learning/learn.py': [Errno 2] No such file or directory

**Comment by timlacroix** [comment]
python kbc/kbc/learning/learn.py would fix the last line.

I'll mark this issue as closed. it's a matter of loading the installed library vs loading the library represented by the folders.

**Comment by p6jain** [comment]
I am getting more FileNotFoundError on running the code from outside the 1st kbc directory.

(kbc_env2) prachi@gpu01:~/related_work/kbc2$ time CUDA_VISISBLE_DEVICES=4 python kbc/kbc/learning/learn.py --dataset FB15K --model ComplEx --rank 2000 --optimizer Adagrad --learning_rate 1e-2 --batch_size 100 --regularizer L3ComplEx --reg 5e-3 --learn_inverse_rels 1 --max_epochs 100 --valid 1
Traceback (most recent call last):
  File "kbc/kbc/learning/learn.py", line 110, in <module>
    }[args.dataset]()
  File "kbc/kbc/learning/learn.py", line 103, in <lambda>
    'FB15K': lambda : big.FB15KDataset(iv, args.prop_kept),
  File "/home/prachi/anaconda3/envs/kbc_env2/lib/python3.6/site-packages/kbc-0.0.0-py3.6-linux-x86_64.egg/kbc/datasets/big.py", line 182, in __init__
    self.load(prop_kept)
  File "/home/prachi/anaconda3/envs/kbc_env2/lib/python3.6/site-packages/kbc-0.0.0-py3.6-linux-x86_64.egg/kbc/datasets/big.py", line 97, in load
    train_file = open(os.path.join(self.root, 'train'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/prachi/anaconda3/envs/kbc_env2/lib/python3.6/site-packages/kbc-0.0.0-py3.6-linux-x86_64.egg/kbc/data/FB15K/train'

**Comment by timlacroix** [comment]
follow the remainder of the readme to process the datasets. Make sure they were put in the data folder in site-packages.

(also typo in CUDA_VISIBLE_DEVICES)
