### ISSUE TITLE
How I can use my own datasets？

### ISSUE THREAD

**Issue by Wilson-ZHANG** [facebookresearch/kbc#5]
I plus my datasets in /data and then python datasets/process_datasets.py
but I still need change some code in kbc/learning/learn.py, especially the line102 dataset={'FB15K': lambda : big.FB15KDataset(iv, args.prop_kept),
 'FB237': lambda : big.FB237Dataset(iv, args.prop_kept),
 'WN': lambda : big.WNDataset(iv),
 'WN18RR': lambda : big.WN18RRDataset(iv),
 'SVO': lambda : big.SVODataset(iv),
 'YAGO': lambda : big.YAGO310Dataset(iv),
 'UMLS': lambda : small.UMLSDataset(iv),
 'MY_DATASET': lambda : ????????(iv),}

Could you teach me in the place of ???????
Thanks a lot.

**Comment by timlacroix** [comment]
Hi,
To add your own dataset, feel free to look at the code in datasets.big (for example the FB237Dataset class) and add your own (not much to do, and it should be easy to add a generic class that takes as input the name of the dataset)

You can then use it in place of the ????
