### ISSUE TITLE
Wrong data folder name

### ISSUE THREAD

**Issue by dschaehi** [facebookresearch/kbc#8]
Hi,

When I run `process_datasets.py` it complains that folder `src_data` does not exist. I think the data folder name should be `data` and not `src_data`.

https://github.com/facebookresearch/kbc/blob/729f18342f7e44de6c2d1aa19c28bdd4314d7ff2/kbc/process_datasets.py#L116

**Comment by timlacroix** [comment]
Oops, forgot to push some changes in download_data.sh

I renamed the "data" folder to avoid name conflicts between the "data" folder of the package and the "data" folder previously created by the script.

Hopefully the latest push should fix your issue.
