### ISSUE TITLE
Can't match performance reported in paper with pytorch code

### ISSUE THREAD

**Issue by p6jain** [facebookresearch/kbc#9]
As advised, I doubled the reg penalty, but I am still not able to match the performance reported in the paper, with the new code.

**Complex on FB15k (rank 2000):**
```
python kbc/learn.py --dataset FB15K --model ComplEx --rank 2000 --optimizer Adagrad --learning_rate 1e-2 --batch_size 20000 --regularizer N3 --reg 1e-2 --max_epochs 100 --valid 1
```
TEST :  ({'rhs': 0.8638818860054016, 'lhs': 0.8191012144088745}, {'rhs': tensor([0.8245, 0.8918, 0.9291]), 'lhs': tensor([0.7801, 0.8433, 0.8840])})

**Complex on Yago3-10 (rank 1000)**:
```
python kbc/learn.py --dataset YAGO3-10 --model ComplEx --rank 1000 --optimizer Adagrad --learning_rate 1e-1 --batch_size 1500 --regularizer N3 --reg 1e-1 --max_epochs 100 --valid 1 
```
TEST :  ({'rhs': 0.46305328607559204, 'lhs': 0.1873369812965393}, {'rhs': tensor([0.3494, 0.5212, 0.6812]), 'lhs': tensor([0.1132, 0.2090, 0.3326])})

Please advise on what may be going wrong.

**Comment by timlacroix** [comment]
I'm not too worried about the FB15K perfs which are not too far (0.84 vs 0.86) from what's in the paper  (your batch_size 20000 is a little extreme). 
However the YAGO perfs seem really far indeed.

I'll re-run a grid-search on both of these datasets today.

**Comment by timlacroix** [comment]
For YAGO, you went from reg=1e-2 advised in the README to reg=1e-1. That's not a factor of two but a factor of 10.

**Comment by timlacroix** [comment]
after grid search, for YAGO I suggest running 50 epochs using :
rank 1000
reg 5e-3
batch_size 1000

I'll update the parameters for FB15K as soon as I'm back from holidays. In the meantime you can try decreasing the batch-size.

**Comment by timlacroix** [comment]
Hey, I finally re-ran some grid searches for all datasets. I updated the README with the parameters
